import { msg } from "../../i18n";
import type { Feature } from "../features";
const features: Feature[] = [
  { id: "orc-measure:loa-min", label: msg("Minimum Length overall (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:loa-max", label: msg("Maximum Length overall (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:beam-min", label: msg("Minimum Beam (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:beam-max", label: msg("Maximum Beam (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:draft-min", label: msg("Minimum Draft (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:draft-max", label: msg("Maximum Draft (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:displacement-min", label: msg("Minimum Displacement (kg)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:displacement-max", label: msg("Maximum Displacement (kg)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:main-min", label: msg("Minimum Mainsail area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:main-max", label: msg("Maximum Mainsail area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:genoa-min", label: msg("Minimum Genoa area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:genoa-max", label: msg("Maximum Genoa area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:spinnaker-min", label: msg("Minimum Spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:spinnaker-max", label: msg("Maximum Spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:asymmetric-min", label: msg("Minimum Asymmetric spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc-measure:asymmetric-max", label: msg("Maximum Asymmetric spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields", "orc:measurements"] },
  { id: "orc:more", label: msg("More certificates"), description: msg("The next page of the search; it loads on its own as the results are scrolled to their end."), keywords: [msg("page"), msg("scroll"), msg("results")], topic: "orc", reveal: ["section:orc", "orc:results"] },
  { id: "orc:measurements", label: msg("Measurements"), description: msg("Unfold the measurement bounds under Search by field: a minimum and a maximum for each of the boat's measurements."), keywords: [msg("length"), msg("beam"), msg("draft"), msg("displacement"), "LOA"], topic: "orc", reveal: ["section:orc", "orc:fields"] },
];
export default features;
