import { msg } from "../../i18n";
import type { Feature } from "../features";
const features: Feature[] = [
  { id: "orc-measure:loa-min", label: msg("Minimum Length overall (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:loa-max", label: msg("Maximum Length overall (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:beam-min", label: msg("Minimum Beam (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:beam-max", label: msg("Maximum Beam (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:draft-min", label: msg("Minimum Draft (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:draft-max", label: msg("Maximum Draft (m)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:displacement-min", label: msg("Minimum Displacement (kg)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:displacement-max", label: msg("Maximum Displacement (kg)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:main-min", label: msg("Minimum Mainsail area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:main-max", label: msg("Maximum Mainsail area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:genoa-min", label: msg("Minimum Genoa area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:genoa-max", label: msg("Maximum Genoa area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:spinnaker-min", label: msg("Minimum Spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:spinnaker-max", label: msg("Maximum Spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:asymmetric-min", label: msg("Minimum Asymmetric spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:asymmetric-max", label: msg("Maximum Asymmetric spinnaker area (m\u00b2)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:crew-min", label: msg("Minimum Crew weight (kg)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc-measure:crew-max", label: msg("Maximum Crew weight (kg)"), description: msg("Filter certificates by their measured dimensions. Missing measurements do not pass an active bound."), keywords: [msg("Measurements")], topic: "orc", reveal: ["section:orc", "orc:fields"] },
  { id: "orc:previous-page", label: msg("Previous"), description: msg("Browse another page of matching polar certificates."), keywords: [msg("Search results")], topic: "orc", reveal: ["section:orc", "orc:results"] },
  { id: "orc:next-page", label: msg("Next"), description: msg("Browse another page of matching polar certificates."), keywords: [msg("Search results")], topic: "orc", reveal: ["section:orc", "orc:results"] },
];
export default features;
