import { msg } from "../../i18n";
import type { Feature } from "../features";

/**
 * The Tracks section of the left navigation (spec.md 7.1, 7.4, 7.6). A
 * track's filters and derivation show once the track is unfolded, which the
 * `track:details` step does for the first track. The import dialog's
 * controls exist only once files are chosen, so they land on File…
 * (`landing`), and each description says so; the tracker dialog's land on
 * YellowBrick… the same way.
 */
const section = ["section:tracks"];
const details = ["section:tracks", "track:details"];
const topic = "tracks";
const environment = "environment";
const trackers = "trackers";
/** The tracker dialog's controls exist only once it is open: they land on its button. */
const dialog = { topic: trackers, reveal: section, landing: "tracks:yellowbrick" };

const features: Feature[] = [
  { id: "tracks:import-file", label: msg("Import track files"),
    description: msg("Import GeoJSON and CSV tracks, several files at once, choosing the boats and mapping the columns."),
    keywords: [msg("import"), "GeoJSON", "CSV", msg("race"), msg("positions"), msg("column mapping"), msg("boat picker"),
      msg("time format"), msg("speed unit")], topic, reveal: section },
  { id: "tracks:yellowbrick", label: msg("YellowBrick import"), description: msg("Import boats from a YellowBrick race: paste its yb.tl link or race key, pick boats from the whole fleet."),
    keywords: [msg("tracker"), msg("race"), "yb.tl", msg("fleet")], topic: trackers, reveal: section },
  { id: "tracks:geovoile", label: msg("Geovoile import"), description: msg("Import boats from a Geovoile race. Arrives in a later version."),
    keywords: [msg("tracker"), msg("race")], topic, reveal: section },
  { id: "tracks:bluewater", label: msg("Blue Water Tracks import"), description: msg("Import boats from Blue Water Tracks. Arrives in a later version."),
    keywords: [msg("tracker"), msg("race")], topic, reveal: section },
  { id: "tracks:show-on-map", label: msg("Show track on the map"), description: msg("Frame one track on the map."),
    keywords: [msg("map"), msg("zoom"), msg("track")], topic, reveal: section },
  { id: "tracks:filters", label: msg("Track filters"), description: msg("Unfold a track's sample filters and heading and speed derivation."),
    keywords: [msg("filters"), msg("settings"), msg("track")], topic, reveal: section },
  { id: "tracks:remove", label: msg("Remove track"), description: msg("Remove a track from the project. Undo puts it back."),
    keywords: [msg("delete"), msg("remove")], topic, reveal: section },
  { id: "tracks:refetch", label: msg("Refetch environment"), description: msg("Fetch a track's wind, waves and current: the missing samples, or all of them again once it is ready."),
    keywords: [msg("reanalysis"), msg("wind"), msg("resume")], topic: environment, reveal: details },
  { id: "tracks:cancel-fetch", label: msg("Cancel a track's fetch"), description: msg("While a track's environment is being fetched, stop it; the samples already fetched are kept."),
    keywords: [msg("stop"), msg("reanalysis"), msg("job")], topic: environment, reveal: details, landing: "tracks:refetch" },
  { id: "env-fetch:hourly", label: msg("Hourly sampling"), description: msg("In the fetch dialog (Refetch environment first): read the wind and waves of every hour."),
    keywords: [msg("interval"), msg("download size"), "ERA5"], topic: environment, reveal: details, landing: "tracks:refetch" },
  { id: "env-fetch:three-hourly", label: msg("3-hourly sampling"), description: msg("In the fetch dialog (Refetch environment first): read every third hour and interpolate, a third of the download."),
    keywords: [msg("interval"), msg("download size"), msg("long race")], topic: environment, reveal: details, landing: "tracks:refetch" },
  { id: "tracks:use-corrected", label: msg("Correct for current"), description: msg("Feed the polar from boat speed and wind through the water where a current was found."),
    keywords: [msg("current"), msg("tide"), "BSP"], topic: environment, reveal: section },
  { id: "tracks:stokes-drift", label: msg("Include Stokes drift"), description: msg("Add the waves' Stokes drift to the global merged current, from the next fetch."),
    keywords: [msg("current"), msg("waves")], topic: environment, reveal: section },
  { id: "tracks:export-grib", label: msg("Export reanalysis GRIB"), description: msg("Write the wind along a track to a GRIB file. Arrives in a later version."),
    keywords: ["GRIB", msg("export"), msg("wind")], topic, reveal: details },
  { id: "tracks:time-start", label: msg("Time window start"), description: msg("Leave out samples before this time, such as before the start."),
    keywords: [msg("time window"), msg("start"), msg("filters")], topic, reveal: details },
  { id: "tracks:time-end", label: msg("Time window end"), description: msg("Leave out samples after this time, such as after the finish."),
    keywords: [msg("time window"), msg("finish"), msg("filters")], topic, reveal: details },
  { id: "tracks:min-bsp", label: msg("Minimum boat speed"), description: msg("Leave out samples slower than this (1 kn by default)."),
    keywords: ["BSP", msg("filters"), msg("slow")], topic, reveal: details },
  { id: "tracks:max-bsp", label: msg("Maximum boat speed"), description: msg("Leave out samples faster than this."),
    keywords: ["BSP", msg("filters"), msg("fast")], topic, reveal: details },
  { id: "tracks:manoeuvre", label: msg("Manoeuvre threshold"), description: msg("Leave out samples whose heading changes more than this between neighbours (30° by default)."),
    keywords: [msg("tack"), msg("gybe"), msg("filters")], topic, reveal: details },
  { id: "tracks:heading-origin", label: msg("Given or derived heading"), description: msg("Keep samples whose heading the track gave, was derived, or either."),
    keywords: [msg("heading"), "COG", msg("filters")], topic, reveal: details },
  { id: "tracks:speed-origin", label: msg("Given or derived speed"), description: msg("Keep samples whose speed the track gave, was derived, or either."),
    keywords: [msg("speed"), "SOG", msg("filters")], topic, reveal: details },
  { id: "tracks:tws-min", label: msg("Minimum TWS"), description: msg("Leave out samples in less wind than this."),
    keywords: ["TWS", msg("wind"), msg("filters")], topic, reveal: details },
  { id: "tracks:tws-max", label: msg("Maximum TWS"), description: msg("Leave out samples in more wind than this."),
    keywords: ["TWS", msg("wind"), msg("filters")], topic, reveal: details },
  { id: "tracks:twa-min", label: msg("Minimum TWA"), description: msg("Leave out samples closer to the wind than this."),
    keywords: ["TWA", msg("wind angle"), msg("filters")], topic, reveal: details },
  { id: "tracks:twa-max", label: msg("Maximum TWA"), description: msg("Leave out samples further off the wind than this."),
    keywords: ["TWA", msg("wind angle"), msg("filters")], topic, reveal: details },
  { id: "tracks:hs-min", label: msg("Minimum wave height"), description: msg("Leave out samples in smaller waves than this."),
    keywords: [msg("waves"), msg("sea state"), msg("filters")], topic, reveal: details },
  { id: "tracks:hs-max", label: msg("Maximum wave height"), description: msg("Leave out samples in bigger waves than this."),
    keywords: [msg("waves"), msg("sea state"), msg("filters")], topic, reveal: details },
  { id: "tracks:wave-mode", label: msg("Wave direction filter"), description: msg("Keep samples by where the waves come from: sectors or an angle off the bow, or a compass range."),
    keywords: [msg("waves"), msg("head seas"), msg("following seas"), msg("filters")], topic, reveal: details },
  { id: "tracks:wave-sectors", label: msg("Wave sectors"), description: msg("With the wave direction filter on sectors: head, bow, beam, quarter or following seas."),
    keywords: [msg("waves"), msg("beam"), msg("quarter")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-min", label: msg("Minimum wave angle"), description: msg("With the wave direction filter on an angle off the bow: the smallest kept, 0° head seas."),
    keywords: [msg("waves"), msg("angle")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-max", label: msg("Maximum wave angle"), description: msg("With the wave direction filter on an angle off the bow: the largest kept, 180° following seas."),
    keywords: [msg("waves"), msg("angle")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-from", label: msg("Waves from"), description: msg("With the wave direction filter on a compass range: where it starts, clockwise."),
    keywords: [msg("waves"), msg("compass")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-to", label: msg("Waves to"), description: msg("With the wave direction filter on a compass range: where it ends."),
    keywords: [msg("waves"), msg("compass")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:current-min", label: msg("Minimum current"), description: msg("Leave out samples in less current than this."),
    keywords: [msg("current"), msg("tide"), msg("filters")], topic, reveal: details },
  { id: "tracks:current-max", label: msg("Maximum current"), description: msg("Leave out samples in more current than this."),
    keywords: [msg("current"), msg("tide"), msg("filters")], topic, reveal: details },
  { id: "tracks:no-tide", label: msg("Leave out currents without tide"), description: msg("Leave out samples whose current comes from a source marked without tide (none of today's sources is)."),
    keywords: [msg("current"), msg("tide"), msg("filters")], topic: environment, reveal: details },
  { id: "tracks:max-gap", label: msg("Maximum gap"), description: msg("Neighbours further apart in time than this are not used to derive heading and speed (3 h by default)."),
    keywords: [msg("derivation"), msg("gap"), msg("heading"), msg("speed")], topic, reveal: details },
  { id: "tracks:prefer", label: msg("Prefer given or derived"), description: msg("Use the heading and speed a track gives, or always derive them from the positions."),
    keywords: [msg("derivation"), "COG", "SOG"], topic, reveal: details },
  { id: "track-import:time", label: msg("Time column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column the times are read from."),
    keywords: ["CSV", msg("column"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:lat", label: msg("Latitude column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column the latitudes are read from."),
    keywords: ["CSV", msg("column"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:lon", label: msg("Longitude column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column the longitudes are read from."),
    keywords: ["CSV", msg("column"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:heading", label: msg("Heading column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column with the heading or COG, if any."),
    keywords: ["CSV", "COG", msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:speed", label: msg("Speed column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column with the SOG or boat speed, if any."),
    keywords: ["CSV", "SOG", msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:boat", label: msg("Boat column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column naming the boat, for a file with several boats."),
    keywords: ["CSV", msg("boat"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:time-format", label: msg("Time format"), description: msg("Inside the track import dialog (choose files with File… first): how the CSV's times are written."),
    keywords: ["ISO 8601", msg("epoch"), msg("date")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:custom-format", label: msg("Custom time format"), description: msg("Inside the track import dialog (choose files with File… first): a pattern such as %d/%m/%Y %H:%M for the times."),
    keywords: [msg("pattern"), msg("date")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:speed-unit", label: msg("Speed unit"), description: msg("Inside the track import dialog (choose files with File… first): the unit of the CSV's speed column."),
    keywords: [msg("knots"), "km/h", "m/s"], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:boats", label: msg("Boats in this file"), description: msg("Inside the track import dialog (choose files with File… first): tick the boats to import from a file with several."),
    keywords: [msg("boat picker"), msg("choose")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "tracker-import:url", label: msg("Event address"), description: msg("In the tracker dialog (YellowBrick… first): paste the race's link or key."),
    keywords: [msg("link"), msg("race key"), "yb.tl", msg("paste")], ...dialog },
  { id: "tracker-import:open", label: msg("Open the event"), description: msg("In the tracker dialog (YellowBrick… first): download every boat's full track, or open the event kept from earlier in this session."),
    keywords: [msg("download"), msg("fleet"), msg("tracker")], ...dialog },
  { id: "tracker-import:cancel-download", label: msg("Cancel the download"), description: msg("In the tracker dialog, while an event downloads: stop it; nothing is imported."),
    keywords: [msg("stop"), msg("download"), msg("job")], ...dialog },
  { id: "tracker-import:retry", label: msg("Retry the download"), description: msg("In the tracker dialog, after a failed download: ask the tracker again."),
    keywords: [msg("again"), msg("error"), msg("download")], ...dialog },
  { id: "tracker-import:refresh", label: msg("Download the event again"), description: msg("In the tracker dialog, for an event kept from earlier in this session: download it again for newer positions."),
    keywords: [msg("refresh"), msg("update"), msg("download")], ...dialog },
  { id: "tracker-import:search", label: msg("Search the fleet"), description: msg("In the tracker dialog, once an event is open: show only the boats whose name, sail number, model or division contains the words typed."),
    keywords: [msg("find"), msg("sail number"), msg("division"), msg("boat")], ...dialog },
  { id: "tracker-import:boats", label: msg("Boats of the event"), description: msg("In the tracker dialog, once an event is open: every boat with its sail number, model, division, positions and status; tick the ones to import."),
    keywords: [msg("boat picker"), msg("choose"), msg("fleet")], ...dialog },
  { id: "tracker-import:select-shown", label: msg("Tick every boat shown"), description: msg("In the tracker dialog, once an event is open: tick or untick every boat the search shows."),
    keywords: [msg("select all"), msg("choose"), msg("fleet")], ...dialog },
];

export default features;
