import { msg } from "../../i18n";
import type { Feature } from "../features";

/**
 * The Tracks section of the left navigation (spec.md 7.1, 7.4, 7.6). A
 * track's filters and derivation show once the track is unfolded, which the
 * `track:details` step does for the first track. The import dialog's
 * controls exist only once files are chosen, so they land on File…
 * (`landing`), and each description says so; the tracker dialog's land on
 * YellowBrick… the same way.
 */
const section = ["section:tracks"];
const details = ["section:tracks", "track:details"];
const topic = "tracks";
const environment = "environment";
const trackers = "trackers";
/** The tracker dialog's controls exist only once it is open: they land on its button. */
const dialog = { topic: trackers, reveal: section, landing: "tracks:yellowbrick" };

const features: Feature[] = [
  { id: "tracks:awa-change", label: msg("AWA change (°)"), description: msg("Exclude points when apparent wind angle changes by more than this from the previous or next point."), keywords: ["AWA", msg("filters")], topic, reveal: details },
  { id: "tracks:wind-speed-change", label: msg("True wind speed"), description: msg("Exclude points when true wind speed changes by more than this from the previous or next point."), keywords: ["TWS", msg("filters")], topic, reveal: details },
  { id: "tracks:wind-direction-change", label: msg("Wind direction change (°)"), description: msg("Exclude points when true wind direction changes by more than this from the previous or next point."), keywords: ["TWD", msg("filters")], topic, reveal: details },
  { id: "tracks:wind-source", label: msg("Wind: provided or downloaded"), description: msg("Use the wind the track provides where it has both speed and direction, or the downloaded weather everywhere. Shown only for a track that provides wind."), keywords: ["TWS", "TWD", msg("wind"), msg("provided"), msg("derived")], topic, reveal: details },
  { id: "tracks:heading-source", label: msg("Heading: provided or derived"), description: msg("Use the heading the track provides, or one derived from its positions. Shown only for a track that provides headings."), keywords: [msg("heading"), "COG", msg("provided"), msg("derived")], topic, reveal: details },
  { id: "tracks:speed-source", label: msg("Speed: provided or derived"), description: msg("Use the speed the track provides, or one derived from its positions. Shown only for a track that provides speeds."), keywords: [msg("speed"), "SOG", msg("provided"), msg("derived")], topic, reveal: details },
  { id: "tracks:vmg-min", label: msg("Minimum VMG"), description: msg("Leave out samples making less to windward than this: VMG is BSP × cos TWA, negative downwind."), keywords: ["VMG", msg("filters")], topic, reveal: details },
  { id: "tracks:vmg-max", label: msg("Maximum VMG"), description: msg("Leave out samples making more to windward than this."), keywords: ["VMG", msg("filters")], topic, reveal: details },
  { id: "tracks:heading-from", label: msg("Heading from"), description: msg("Keep samples heading from this compass direction clockwise to the next, through the water where the current is corrected for."), keywords: [msg("heading"), msg("compass"), msg("filters")], topic, reveal: details },
  { id: "tracks:heading-to", label: msg("Heading to"), description: msg("The end of the heading sector kept."), keywords: [msg("heading"), msg("compass"), msg("filters")], topic, reveal: details },
  { id: "tracks:cog-from", label: msg("COG from"), description: msg("Keep samples whose course over the ground runs from this compass direction clockwise to the next."), keywords: ["COG", msg("course"), msg("filters")], topic, reveal: details },
  { id: "tracks:cog-to", label: msg("COG to"), description: msg("The end of the course sector kept."), keywords: ["COG", msg("course"), msg("filters")], topic, reveal: details },
  { id: "tracks:twd-from", label: msg("TWD from"), description: msg("Keep samples whose true wind comes from this compass direction clockwise to the next."), keywords: ["TWD", msg("wind direction"), msg("filters")], topic, reveal: details },
  { id: "tracks:twd-to", label: msg("TWD to"), description: msg("The end of the wind direction sector kept."), keywords: ["TWD", msg("wind direction"), msg("filters")], topic, reveal: details },
  { id: "tracks:tacks", label: msg("Remove tacks and gybes"), description: msg("Leave out the sample on either side of each tack and gybe, where the wind crosses the bow or the stern between neighbours."), keywords: [msg("tack"), msg("gybe"), msg("filters")], topic, reveal: details },
  { id: "track-import:tws", label: msg("True wind speed"), description: msg("Supplied wind where available"), keywords: ["CSV", "TWS", msg("column")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:twd", label: msg("True wind direction"), description: msg("Supplied wind where available"), keywords: ["CSV", "TWD", msg("column")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:wind-speed-unit", label: msg("Wind speed unit"), description: msg("Supplied wind where available"), keywords: ["CSV", "TWS", msg("knots")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "tracks:unknown-wave", label: msg("Exclude unknown waves"), description: msg("Exclude samples without wave height or direction."), keywords: [msg("filters"), msg("track")], topic, reveal: details },
  { id: "tracks:unknown-current", label: msg("Exclude unknown current"), description: msg("Exclude samples without current speed or direction."), keywords: [msg("filters"), msg("track")], topic, reveal: details },

  { id: "tracks:import-file", label: msg("Import track files"),
    description: msg("Import GeoJSON and CSV tracks, several files at once, choosing the boats and mapping the columns."),
    keywords: [msg("import"), "GeoJSON", "CSV", msg("race"), msg("positions"), msg("column mapping"), msg("boat picker"),
      msg("time format"), msg("speed unit")], topic, reveal: section },
  { id: "tracks:yellowbrick", label: msg("YellowBrick import"), description: msg("Import boats from a YellowBrick race: paste its yb.tl link or race key, pick boats from the whole fleet."),
    keywords: [msg("tracker"), msg("race"), "yb.tl", msg("fleet")], topic: trackers, reveal: section },
  { id: "tracks:geovoile", label: msg("Geovoile import"), description: msg("Import boats from a Geovoile race (2016 on): paste its viewer address, one leg at a time for a race in legs, and pick boats from the whole fleet."),
    keywords: [msg("tracker"), msg("race"), "geovoile.com", msg("fleet"), msg("leg")], topic: trackers, reveal: section },
  { id: "tracks:bluewater", label: msg("Blue Water Tracks import"), description: msg("Import boats from a Blue Water Tracks race: paste its race.bluewatertracks.com link or race key, pick boats from the whole fleet."),
    keywords: [msg("tracker"), msg("race"), "bluewatertracks.com", msg("fleet")], topic: trackers, reveal: section },
  { id: "tracks:show-on-map", label: msg("Show track on the map"), description: msg("Frame one track on the map."),
    keywords: [msg("map"), msg("zoom"), msg("track")], topic, reveal: section },
  { id: "tracks:filters", label: msg("Track filters"), description: msg("Unfold a track's sample filters and heading and speed derivation."),
    keywords: [msg("filters"), msg("settings"), msg("track")], topic, reveal: section },
  { id: "tracks:remove", label: msg("Remove track"), description: msg("Remove a track from the project. Undo puts it back."),
    keywords: [msg("delete"), msg("remove")], topic, reveal: section },
  { id: "tracks:fetch-weather", label: msg("Fetch weather"), description: msg("Fetch a track's wind, waves and current: the missing samples, or all of them again once it is ready. Importing never does it."),
    keywords: [msg("reanalysis"), msg("wind"), msg("environment"), msg("resume")], topic: environment, reveal: section },
  { id: "tracks:select-all", label: msg("Select all imported tracks"), description: msg("Select all imported tracks for weather download"),
    keywords: [msg("select all"), msg("weather"), msg("several")], topic: environment, reveal: section },
  { id: "tracks:select", label: msg("Select tracks"), description: msg("Tick tracks to fetch their weather together with Fetch weather for selected tracks."),
    keywords: [msg("select"), msg("weather"), msg("several")], topic: environment, reveal: section },
  { id: "tracks:fetch-weather-selected", label: msg("Fetch weather for selected tracks"), description: msg("Fetch the wind, waves and current of every ticked track, one after another, after one download estimate."),
    keywords: [msg("reanalysis"), msg("wind"), msg("environment"), msg("several")], topic: environment, reveal: section },
  { id: "tracks:cancel-fetch", label: msg("Cancel a track's fetch"), description: msg("While a track's weather is being fetched, stop it; the samples already fetched are kept."),
    keywords: [msg("stop"), msg("reanalysis"), msg("job")], topic: environment, reveal: section, landing: "tracks:fetch-weather" },
  { id: "env-fetch:hourly", label: msg("Hourly sampling"), description: msg("In the fetch dialog (Fetch weather first): read the wind and waves of every hour."),
    keywords: [msg("interval"), msg("download size"), "ERA5"], topic: environment, reveal: section, landing: "tracks:fetch-weather" },
  { id: "env-fetch:three-hourly", label: msg("3-hourly sampling"), description: msg("In the fetch dialog (Fetch weather first): read every third hour and interpolate, a third of the download."),
    keywords: [msg("interval"), msg("download size"), msg("long race")], topic: environment, reveal: section, landing: "tracks:fetch-weather" },
  { id: "tracks:use-corrected", label: msg("Correct for current"), description: msg("Feed the polar from boat speed and wind through the water where a current was found."),
    keywords: [msg("current"), msg("tide"), "BSP"], topic: environment, reveal: section },
  { id: "tracks:time-start", label: msg("Time window start"), description: msg("Leave out samples before this time, such as before the start."),
    keywords: [msg("time window"), msg("start"), msg("motoring"), msg("filters")], topic, reveal: details },
  { id: "tracks:time-end", label: msg("Time window end"), description: msg("Leave out samples after this time, such as after the finish."),
    keywords: [msg("time window"), msg("finish"), msg("motoring"), msg("filters")], topic, reveal: details },
  { id: "tracks:min-bsp", label: msg("Minimum boat speed"), description: msg("Leave out samples slower than this (1 kn by default)."),
    keywords: ["BSP", msg("filters"), msg("slow")], topic, reveal: details },
  { id: "tracks:max-bsp", label: msg("Maximum boat speed"), description: msg("Leave out samples faster than this."),
    keywords: ["BSP", msg("filters"), msg("fast")], topic, reveal: details },
  { id: "tracks:manoeuvre", label: msg("Manoeuvre threshold"), description: msg("Leave out samples whose heading changes more than this between neighbours (30° by default)."),
    keywords: [msg("tack"), msg("gybe"), msg("filters")], topic, reveal: details },
  { id: "tracks:tws-min", label: msg("Minimum TWS"), description: msg("Leave out samples in less wind than this."),
    keywords: ["TWS", msg("wind"), msg("filters")], topic, reveal: details },
  { id: "tracks:tws-max", label: msg("Maximum TWS"), description: msg("Leave out samples in more wind than this."),
    keywords: ["TWS", msg("wind"), msg("filters")], topic, reveal: details },
  { id: "tracks:twa-min", label: msg("Minimum TWA"), description: msg("Leave out samples closer to the wind than this."),
    keywords: ["TWA", msg("wind angle"), msg("upwind"), msg("filters")], topic, reveal: details },
  { id: "tracks:twa-max", label: msg("Maximum TWA"), description: msg("Leave out samples further off the wind than this."),
    keywords: ["TWA", msg("wind angle"), msg("downwind"), msg("filters")], topic, reveal: details },
  { id: "tracks:hs-min", label: msg("Minimum wave height"), description: msg("Leave out samples in smaller waves than this."),
    keywords: [msg("waves"), msg("sea state"), msg("swell"), msg("filters")], topic, reveal: details },
  { id: "tracks:hs-max", label: msg("Maximum wave height"), description: msg("Leave out samples in bigger waves than this."),
    keywords: [msg("waves"), msg("sea state"), msg("swell"), msg("filters")], topic, reveal: details },
  { id: "tracks:wave-mode", label: msg("Wave direction filter"), description: msg("Keep samples by where the waves come from: sectors or an angle off the bow, or a compass range."),
    keywords: [msg("waves"), msg("head seas"), msg("following seas"), msg("filters")], topic, reveal: details },
  { id: "tracks:wave-sectors", label: msg("Wave sectors"), description: msg("With the wave direction filter on sectors: head, bow, beam, quarter or following seas."),
    keywords: [msg("waves"), msg("beam"), msg("quarter")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-min", label: msg("Minimum wave angle"), description: msg("With the wave direction filter on an angle off the bow: the smallest kept, 0° head seas."),
    keywords: [msg("waves"), msg("angle")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-max", label: msg("Maximum wave angle"), description: msg("With the wave direction filter on an angle off the bow: the largest kept, 180° following seas."),
    keywords: [msg("waves"), msg("angle")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-from", label: msg("Waves from"), description: msg("With the wave direction filter on a compass range: where it starts, clockwise."),
    keywords: [msg("waves"), msg("compass")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:wave-to", label: msg("Waves to"), description: msg("With the wave direction filter on a compass range: where it ends."),
    keywords: [msg("waves"), msg("compass")], topic, reveal: details, landing: "tracks:wave-mode" },
  { id: "tracks:current-min", label: msg("Minimum current"), description: msg("Leave out samples in less current than this."),
    keywords: [msg("current"), msg("tide"), msg("filters")], topic, reveal: details },
  { id: "tracks:current-max", label: msg("Maximum current"), description: msg("Leave out samples in more current than this."),
    keywords: [msg("current"), msg("tide"), msg("filters")], topic, reveal: details },
  { id: "tracks:no-tide", label: msg("Leave out currents without tide"), description: msg("Leave out samples whose current comes from a source marked without tide (none of today's sources is)."),
    keywords: [msg("current"), msg("tide"), msg("filters")], topic: environment, reveal: details },
  { id: "track-import:time", label: msg("Time column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column the times are read from."),
    keywords: ["CSV", msg("column"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:lat", label: msg("Latitude column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column the latitudes are read from."),
    keywords: ["CSV", msg("column"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:lon", label: msg("Longitude column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column the longitudes are read from."),
    keywords: ["CSV", msg("column"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:heading", label: msg("Heading column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column with the heading or COG, if any."),
    keywords: ["CSV", "COG", msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:speed", label: msg("Speed column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column with the SOG or boat speed, if any."),
    keywords: ["CSV", "SOG", msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:boat", label: msg("Boat column"), description: msg("Inside the track import dialog (choose files with File… first): the CSV column naming the boat, for a file with several boats."),
    keywords: ["CSV", msg("boat"), msg("mapping")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:time-format", label: msg("Time format"), description: msg("Inside the track import dialog (choose files with File… first): how the CSV's times are written."),
    keywords: ["ISO 8601", msg("epoch"), msg("date")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:custom-format", label: msg("Custom time format"), description: msg("Inside the track import dialog (choose files with File… first): a pattern such as %d/%m/%Y %H:%M for the times."),
    keywords: [msg("pattern"), msg("date")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:speed-unit", label: msg("Speed unit"), description: msg("Inside the track import dialog (choose files with File… first): the unit of the CSV's speed column."),
    keywords: [msg("knots"), "km/h", "m/s"], topic, reveal: section, landing: "tracks:import-file" },
  { id: "track-import:boats", label: msg("Boats in this file"), description: msg("Inside the track import dialog (choose files with File… first): tick the boats to import from a file with several."),
    keywords: [msg("boat picker"), msg("choose")], topic, reveal: section, landing: "tracks:import-file" },
  { id: "tracker-import:url", label: msg("Event address"), description: msg("In the tracker dialog (YellowBrick… first): paste the race's link or key."),
    keywords: [msg("link"), msg("race key"), "yb.tl", msg("paste")], ...dialog },
  { id: "tracker-import:open", label: msg("Open the event"), description: msg("In the tracker dialog (YellowBrick… first): download every boat's track, without weather, or open the event kept from earlier in this session. The boats list as soon as the tracker names them."),
    keywords: [msg("download"), msg("fleet"), msg("tracker")], ...dialog },
  { id: "tracker-import:retry", label: msg("Retry the download"), description: msg("In the tracker dialog, after a failed download: ask the tracker again."),
    keywords: [msg("again"), msg("error"), msg("download")], ...dialog },
  { id: "tracker-import:refresh", label: msg("Download the event again"), description: msg("In the tracker dialog, for an event kept from earlier in this session: download it again for newer positions."),
    keywords: [msg("refresh"), msg("update"), msg("download")], ...dialog },
  { id: "tracker-import:search", label: msg("Search the fleet"), description: msg("In the tracker dialog, once an event is open: show only the boats whose name, sail number, model or division contains the words typed."),
    keywords: [msg("find"), msg("sail number"), msg("division"), msg("boat")], ...dialog },
  { id: "tracker-import:boats", label: msg("Boats of the event"), description: msg("In the tracker dialog, once an event is open: every boat with its sail number, model, division, positions and status; tick the ones to import."),
    keywords: [msg("boat picker"), msg("choose"), msg("fleet")], ...dialog },
  { id: "tracker-import:leg", label: msg("Choose the leg"), description: msg("In the tracker dialog, for a Geovoile race sailed in legs: each leg is its own event; choose another to download it."),
    keywords: [msg("leg"), msg("stage"), "Geovoile"], ...dialog },
  { id: "tracker-import:select-shown", label: msg("Tick every boat shown"), description: msg("In the tracker dialog, once an event is open: tick or untick every boat the search shows."),
    keywords: [msg("select all"), msg("choose"), msg("fleet")], ...dialog },
];

const sharedFilterIds = new Set([
  "min-bsp", "max-bsp", "vmg-min", "vmg-max", "heading-from", "heading-to", "cog-from", "cog-to", "twd-from", "twd-to", "tacks",
  "manoeuvre", "awa-change", "wind-speed-change", "wind-direction-change", "unknown-wave", "unknown-current", "tws-min", "tws-max", "twa-min", "twa-max",
  "hs-min", "hs-max", "wave-mode", "wave-sectors", "wave-min", "wave-max", "wave-from", "wave-to", "current-min", "current-max", "no-tide",
]);
const globalFilters = features.filter((f) => sharedFilterIds.has(f.id.slice(7))).map((f) => ({
  ...f, id: f.id.replace("tracks:", "global-filters:"),
  description: msg("Global point filters apply after individual track filters. Open the 3D filter panel to enable or edit them."),
  topic: "polar-3d", reveal: ["stage:3d"], landing: "view3d:global-filters",
}));
const priorityFilters = globalFilters.map((f) => ({
  ...f, id: f.id.replace("global-filters:", "priority-filters:"),
  description: msg("Priority groups are tried in order for each TWA/TWS cell. The first group with enough samples supplies that cell."),
  landing: "view3d:priority-filters",
}));
export default [...features, ...globalFilters, ...priorityFilters];
